# Generated by Django 3.2.13 on 2022-07-04 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_users', '0002_auto_20220704_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_project',
            name='employee_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employee_id', to='employee_users.employee_details'),
            preserve_default=False,
        ),
    ]
